### ISSUE TITLE
test submitter

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/fluidex-backend#51]
submitter is in https://github.com/Fluidex/regnbue-bridge/blob/master/src/tele_out/eth_sender/mod.rs

we deploy the contract by https://github.com/Fluidex/fluidex-backend/blob/master/run.sh#L124

we want to fetch new_root/proof from db and call smart contract to submit a block

**Comment by HAOYUatHZ** [comment]
we also need to modify https://github.com/Fluidex/regnbue-bridge/blob/master/src/tele_out/task_fetcher.rs#L31 accordingly, otherwise it can't pass https://github.com/Fluidex/contracts.demo/blob/master/contracts/Fluidex.sol#L38

**Comment by HAOYUatHZ** [comment]
related: 
+ [ ] https://github.com/Fluidex/fluidex-backend/issues/48
+ [ ] https://github.com/Fluidex/regnbue-bridge/issues/46

**Comment by lightsing** [comment]
related Fluidex/regnbue-bridge#47
