### ISSUE TITLE
restart without cleaning DB

### ISSUE THREAD

**Issue by HAOYUatHZ** [fluidex/fluidex-backend#69]
allow restarting without cleaning DB.

can config “cleaning DB" or "not cleaning DB".

default is "not cleaning DB ".

1. [ ] pg DB
2. [ ] sled DB
3. [ ] need to deal with MQ carefully?

**Comment by HAOYUatHZ** [comment]
if we haven't deleted eth_node blocks locally, we restart without cleaning DB.

if we have deleted eth_node blocks locally, we restart with cleaning DB.

**Comment by lightsing** [comment]
related:
fluidex/regnbue-bridge#73
fluidex/prover-cluster#106
fluidex/contracts.demo#27

**Comment by lightsing** [comment]
still working in progress on testing
